In [2]:
import pandas as pd 
df1=pd.DataFrame({'name':["mosatfa","mohamed","ali"], 'age':[20,30,40]})
df2=pd.DataFrame({'name':["ahmed","gamal","anany"], 'age':[20,30,50]})
df1

      name  age
0  mosatfa   20
1  mohamed   30
2      ali   40

In [15]:
df2

    name  age
0  ahmed   20
1  gamal   30
2  anany   50

In [14]:
df1.merge(df2,on='name',how='outer')

      name  age_x  age_y
0    ahmed    NaN   20.0
1      ali   40.0    NaN
2    anany    NaN   50.0
3    gamal    NaN   30.0
4  mohamed   30.0    NaN
5  mosatfa   20.0    NaN

In [25]:
m=df2.groupby('age')['name'].sum()
m

age
20    ahmed
30    gamal
50    anany
Name: name, dtype: str

#newData frame

In [3]:
data = {
    "Department": ["IT", "HR", "IT", "HR", "Sales", "Sales"],
    "Employee": ["Ali", "Sara", "Omar", "Laila", "Hassan", "Nour"],
    "Salary": [10000, 8000, 12000, 7500, 9000, 9500]
}
df=pd.DataFrame(data)
df

  Department Employee  Salary
0         IT      Ali   10000
1         HR     Sara    8000
2         IT     Omar   12000
3         HR    Laila    7500
4      Sales   Hassan    9000
5      Sales     Nour    9500

In [ ]:
#Grouping by department and salary

In [6]:
df.groupby('Department')['Salary'].sum()

Department
HR       15500
IT       22000
Sales    18500
Name: Salary, dtype: int64